before_script:
  - '[ ! -d $HOME/.nvm ] && git clone http://gitlab.alibaba-inc.com/node/nvm.git $HOME/.nvm'
  - cd $HOME/.nvm && git pull -p && cd -
  - source $HOME/.nvm/nvm.sh
  - nvm i 4 && nvm alias default 4

node-4:
  script:
    - npm i tnpm --registry=http://registry.npm.alibaba-inc.com
    - node_modules/.bin/tnpm ii --install-node=4
    - node_modules/.bin/tnpm run ci
